### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by mindplay-dk** [Codesleuth/vscode-typescript-boilerplate#1]
When I run `npm run-script build` from the root of the project, I get errors.

```
$ npm run-script build

> vscode-typescript-boilerplate@1.1.0 prebuild C:\workspace\test\ts-boilerplate
> rimraf build


> vscode-typescript-boilerplate@1.1.0 build C:\workspace\test\ts-boilerplate
> tsc -p src/ || true

src/typings/main/definitions/sinon/index.d.ts(436,1): error TS2300: Duplicate identifier 'export='.
src/typings/main/definitions/sinon/index.d.ts(440,1): error TS2300: Duplicate identifier 'export='.
src/typings/main/definitions/sinon/index.d.ts(444,1): error TS2300: Duplicate identifier 'export='.
src/typings/modules/sinon/index.d.ts(436,1): error TS2300: Duplicate identifier 'export='.
src/typings/modules/sinon/index.d.ts(440,1): error TS2300: Duplicate identifier 'export='.
src/typings/modules/sinon/index.d.ts(444,1): error TS2300: Duplicate identifier 'export='.
```

When I manually run `tsc` from `src`, I see the same errors.

```
$ tsc
typings/main/definitions/sinon/index.d.ts(436,1): error TS2300: Duplicate identifier 'export='.
typings/main/definitions/sinon/index.d.ts(440,1): error TS2300: Duplicate identifier 'export='.
typings/main/definitions/sinon/index.d.ts(444,1): error TS2300: Duplicate identifier 'export='.
typings/modules/sinon/index.d.ts(436,1): error TS2300: Duplicate identifier 'export='.
typings/modules/sinon/index.d.ts(440,1): error TS2300: Duplicate identifier 'export='.
typings/modules/sinon/index.d.ts(444,1): error TS2300: Duplicate identifier 'export='.
```

This boilerplate works for a CommonJS project only?

I was hoping to find an example/boilerplate for an AMD module in TS with `.d.ts` being generated and exported via `typings`, have you seen such a thing anywhere?

I wrote a [Typescript port](https://bitbucket.org/mindplaydk/scribe-ts/src) of [Scribe](https://github.com/guardian/scribe) and it builds now and emits `.d.ts` etc. - but when I open the generated `.d.ts` or try to compile another project referencing it, I get a long list of errors like `error TS1038: A 'declare' modifier cannot be used in an already ambient context` for the `.d.ts` file.

I'm sorry to ask here, but you seem to know something about this, and I am completely lost - I can't find any documentation or tutorials anywhere explaining how to do this. The closest I've found is your boilerplate project, but like most other examples, this is for CommonJS rather than AMD for the browser. I'm baffled by the fact that the compiler itself seems to generate broken `.d.ts` files without complaint, until you have to actually use the generated file. Please, if you can, point me to anything out there that will help me get started?

**Comment by Codesleuth** [comment]
Hey!

I'll take a look this evening; currently not at a computer. I've done both
(AMD and CommonJS) Typescript projects before and I can probably sorry
something out as a boilerplate for both.

I'll get back to you soon!

Cheers,
Dave

**Comment by Codesleuth** [comment]
I don't seem to get the issue you've listed. What version of Node.js are you using? And what version of Visual Studio Code?

**Comment by Codesleuth** [comment]
Scratch that; managed to duplicate the issue. It seems the major update to [`typings`](https://www.npmjs.com/package/typings) breaks since it's set up for <1.0.0 in this repo. I'll update it for >=1.0.0 which should fix this.

**Comment by Codesleuth** [comment]
I believe I've fixed the issue. Please can you give it a try?

The issue you're speaking about with CommonJS and AMD should probably be reported separately, so I can speak about it further with you in the right context.

**Comment by mindplay-dk** [comment]
Seems to go the same way...

```
$ git pull
<...snip...>
Updating ac0fea8..5e75c38
<...snip...>

$ npm update
typings@1.0.4 node_modules\typings
<...snip...>

$ npm run build

> vscode-typescript-boilerplate@1.2.0 prebuild C:\workspace\test\ts-boilerplate
> rimraf build


> vscode-typescript-boilerplate@1.2.0 build C:\workspace\test\ts-boilerplate
> tsc -p src/ || true

src/typings/main/definitions/sinon/index.d.ts(436,1): error TS2300: Duplicate identifier 'export='.
src/typings/main/definitions/sinon/index.d.ts(440,1): error TS2300: Duplicate identifier 'export='.
src/typings/main/definitions/sinon/index.d.ts(444,1): error TS2300: Duplicate identifier 'export='.
src/typings/modules/sinon/index.d.ts(436,1): error TS2300: Duplicate identifier 'export='.
src/typings/modules/sinon/index.d.ts(440,1): error TS2300: Duplicate identifier 'export='.
src/typings/modules/sinon/index.d.ts(444,1): error TS2300: Duplicate identifier 'export='.

$ tsc -v
Version 1.8.10

$ npm -v
2.14.7

$ node -v
v4.2.2
```

**Comment by Codesleuth** [comment]
Can you make sure you `git clean -xfd` and also ensure your global typings is updated? `npm install -g typings`

The error is due to `typings` moving to version `1.0.4` causing breaking changes with the type definitions included in the repo. I've updated them, and bumped up all versions, but if your global `typings` is updated but you still have the old type definitions in the project, you'll get this error.

**Comment by mindplay-dk** [comment]
`git clean -xfd` and reinstalling with `npm` and `typings` fixed it - it builds :-)

**Comment by mindplay-dk** [comment]
Okay, I'm closing this issue.

You may want to hold off on the AMD boilerplate, I do think there's a [bug](https://github.com/Microsoft/TypeScript/issues/8953) in TS which may be what's tripping me up.

We'll see how they respond...
